name: Auto-Versioning

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
  push:
    branches: 
      - master
    paths-ignore:
      - '.github/workflows/**'
      - 'README.md'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2
      
    - name: Create tag with auto-version
      id: create_tag
      run: |
        v1=$(cat VERSION)
        echo v1: $v1
        v2=$(( ($(date +%y%m%d)) ))
        echo v2: $v2
        v3=$(( ($(date +%H | bc) * 3600) + ($(date +%M | bc) * 60) + ($(date +%S | bc) * 1) ))
        echo v3: $v3
        ver=v$v1.$v2.$v3
        echo ver: $ver
        git tag $ver
        git push origin $ver
        echo Autoversioning done, Tag produced
        echo ::set-output name=tag_autoversion::$ver
        
    - name: Create docker image
      id: docker_image
      run:
        echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login --username ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
#    - name: Create release
#      id: create_release
#      uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ steps.create_tag.outputs.tag_autoversion }}
#        release_name: Release ${{ steps.create_tag.outputs.tag_autoversion }}
#        draft: false
#        prerelease: false
#    - name: Create release asset
#      run: |
#        zip --junk-paths trx-installer ./Install/*
#    - name: Upload release asset
#      id: upload-release-asset 
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: ./trx-installer.zip
#        asset_name: trx-installer.zip
#        asset_content_type: application/zip
